table Planilha1
	lineageTag: 761835d1-6c62-4f68-8269-172faf99fa25

	column Pessoa
		dataType: string
		lineageTag: 90cc718d-1fb3-4d1a-8aca-ce1cceccd1df
		summarizeBy: none
		sourceColumn: Pessoa

		annotation SummarizationSetBy = Automatic

	column idade
		dataType: int64
		formatString: 0
		lineageTag: 52279a4b-466b-4e3e-9f55-e45cd31eba2e
		summarizeBy: sum
		sourceColumn: idade

		annotation SummarizationSetBy = Automatic

	partition Planilha1 = m
		mode: import
		source =
				let
				    Fonte = Excel.Workbook(File.Contents("D:\Documentos\GitHub\dashboard_bitcoin_100criptos\Dados bitcoin.xlsx"), null, true),
				    Planilha1_Sheet = Fonte{[Item="Planilha1",Kind="Sheet"]}[Data],
				    #"Cabeçalhos Promovidos" = Table.PromoteHeaders(Planilha1_Sheet, [PromoteAllScalars=true]),
				    #"Tipo Alterado" = Table.TransformColumnTypes(#"Cabeçalhos Promovidos",{{"Pessoa", type text}, {"idade", Int64.Type}})
				in
				    #"Tipo Alterado"

	annotation PBI_NavigationStepName = Navegação

	annotation PBI_ResultType = Table

